title: Huyen Vu
logo: "photo.png"
description:
  M.S. Data Science
  <br><br>
  <a href="mailto:huyenvu09@outlook.com">Email</a>
  <br><br>
  <a href="https://s3.us-east-1.amazonaws.com/attachments.angel.co/4679739-5a85cb6e50e29a4085f04715698af89a.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJS6W3HGZGRJIRBTA%2F20200616%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200616T155340Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=c3a290fd348e55213caa7072941ce18319d2bbd009480b4821d4af8dc06672ce">Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/huyen-vu-09/">LinkedIn</a>
  <br><br>
  <a href="https://github.com/hvu15?tab=repositories">GitHub</a>
  <br><br>
  <a href="https://observablehq.com/@thanhuyen1809?tab=notebooks&type=public">Observables Notebook</a>

theme: jekyll-theme-minimal
