title: Huyen Vu
logo: "photo.png"
description:
  M.S. Data Science
  <br><br>
  <a href="mailto:huyenvu09@outlook.com">Email</a>
  <br><br>
  <a href="https://s3.us-east-1.amazonaws.com/attachments.angel.co/4686367-3e5aaf8dcce28bd7479bcde5d06b3670.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJS6W3HGZGRJIRBTA%2F20200618%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200618T022915Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=46fbf09aec50f5bdc793ac012abd52b28bb21f48aeed94a96bd05e6cf475bb8c">Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/huyen-vu-09/">LinkedIn</a>
  <br><br>
  <a href="https://github.com/hvu15?tab=repositories">GitHub</a>
  <br><br>
  <a href="https://observablehq.com/@thanhuyen1809?tab=notebooks&type=public">Observables Notebook</a>

theme: jekyll-theme-minimal
