title: <p align="center"> Huyen Vu </p>

logo: "photo.png"

description:
  M.S. Data Science
  <br><br>
  <p align="center">
  <a href="mailto:huyenvu09@outlook.com">Email</a>
  <br><br>
  <a href="resume.pdf">Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/huyen-vu-09/">LinkedIn</a>
  <br><br>
  <a href="https://github.com/hvu15?tab=repositories">GitHub</a>
  <br><br>
  <a href="https://observablehq.com/@thanhuyen1809?tab=notebooks&type=public">Observables Notebook</a>
  </p>

theme: jekyll-theme-minimal
